# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true

android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Keep the app installed after instrumentation test runs
android.injected.androidTest.leaveApksInstalledAfterRun=true
